on:
  pull_request:
    types: [closed]

jobs:
  test:
    name: Check Output
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: |
          echo $GITHUB_REF
          echo $GITHUB_SHA
